---
- name: Install and configure Jenkins
  hosts: localhost

  become: true
  vars:
    jenkins_admin_user: admin  # Change as needed
    jenkins_admin_password: admin  # Change as needed
    jenkins_http_port: 8080  # Change as needed
    jenkins_plugins:
      - name: git
      - name: ansible
      # Add more plugins as needed

  tasks:
    - name: Install Java
      become: true
      package:
        name: java-1.8.0-openjdk
        state: present

    - name: Add Jenkins repository key
      become: true
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      become: true
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Install Jenkins
      become: true
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      become: true
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Wait for Jenkins to start
      become: true
      wait_for:
        port: "{{ jenkins_http_port }}"
        timeout: 60

    - name: Install Jenkins plugins
      become: true
      jenkins_plugin:
        name: "{{ item.name }}"
        state: present
      loop: "{{ jenkins_plugins }}"

    - name: Configure Jenkins admin user
      become: true
      script: configure_jenkins_admin_user.groovy

